name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cppcheck
      uses: deep5050/cppcheck-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
    - name: make
      run: make
