name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: C++ code linter (clang-tidy and cppcheck)
      uses: smay1613/cpp-linter-action@0.0.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: make
      run: make
