name: cppcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cppcheck:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: ProgDroid/cppcheck-action@master
